# Generated by Django 4.1.3 on 2022-11-29 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_value', models.IntegerField(default=0)),
                ('choice_text', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SubscaleClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscaleclass', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('depression', models.CharField(max_length=200)),
                ('anxiety', models.CharField(max_length=200)),
                ('stress', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='date')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('subscaleclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_trytest.subscaleclass')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_answered', models.DateTimeField(verbose_name='date answered')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_trytest.choice')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_trytest.question')),
            ],
        ),
    ]
