# Generated by Django 4.1.3 on 2023-01-08 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to='dassproj/files/profiles'),
        ),
    ]
